del "C:\Git\volt-mx-doc-opnsrc\source\Foundry\vms_console_user_guide\Content\Resources\Images\Settings\Status\message_queue\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Foundry\voltmx_foundry_release_notes\Content\Common\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Foundry\voltmx_foundry_release_notes\Content\Module\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_mac\Content\A_Getting Started\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_mac\Content\B_Links and Lists\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_mac\Content\C_Conditions Notes Tables\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_mac\Content\E_Footer Topics\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_win\Content\A_Getting Started\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_win\Content\B_Links and Lists\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_win\Content\C_Conditions Notes Tables\backup"
del "C:\Git\volt-mx-doc-opnsrc\source\Iris\iris_starter_install_win\Content\E_Footer Topics\backup"

