#!/bin/bash

sh gen_yml.sh app_design_dev Iris
sh gen_yml.sh kony_ref_arch_api Iris
sh gen_yml.sh kony_ref_arch_api_internal Iris
sh gen_yml.sh visualizer_tutorials Iris
sh gen_yml.sh visualizer_user_guide Iris
sh gen_yml.sh viz_api_dev_guide Iris
sh gen_yml.sh viz_app_viewer Iris
sh gen_yml.sh viz_nf_api_dev_guide Iris
sh gen_yml.sh viz_rel_notes Iris
sh gen_yml.sh viz_starter_install_mac Iris
sh gen_yml.sh viz_starter_install_win Iris
sh gen_yml.sh viz_wearables_dev_guide Iris
sh gen_yml.sh viz_widget_prog_guide Iris
