name: Test Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step test
        run: echo "test run.."
      - name: Clean up temporary files
        run: sudo rm -rf /tmp/*
        
